// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.proposals.dao.model.ugap;

import java.io.Serializable;

privileged aspect PeticionTransaccionUgap_Roo_Serializable {
    
    declare parents: PeticionTransaccionUgap implements Serializable;
    
    private static final long PeticionTransaccionUgap.serialVersionUID = 1L;
    
}
