// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.proposals.dao.model.hyt6;

import java.io.Serializable;

privileged aspect FormatoHYMR602_Roo_Serializable {
    
    declare parents: FormatoHYMR602 implements Serializable;
    
    private static final long FormatoHYMR602.serialVersionUID = 1L;
    
}
