// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.proposals.dao.model.ugmp;

import java.io.Serializable;

privileged aspect PeticionTransaccionUgmp_Roo_Serializable {
    
    declare parents: PeticionTransaccionUgmp implements Serializable;
    
    private static final long PeticionTransaccionUgmp.serialVersionUID = 1L;
    
}
