// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.proposals.dao.model.uglp;

import java.io.Serializable;

privileged aspect FormatoUGMSGLP1_Roo_Serializable {
    
    declare parents: FormatoUGMSGLP1 implements Serializable;
    
    private static final long FormatoUGMSGLP1.serialVersionUID = 1L;
    
}
