// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.pzic.proposals.dao.model.uglp;

import java.io.Serializable;

privileged aspect FormatoUGMEGLP_Roo_Serializable {
    
    declare parents: FormatoUGMEGLP implements Serializable;
    
    private static final long FormatoUGMEGLP.serialVersionUID = 1L;
    
}
